### ISSUE TITLE
Adding Interfaces.15.0 ?

### ISSUE THREAD

**Issue by ghost** [jazzdelightsme/UnofficialT4BuildTasks#1]
Microsoft.VisualStudio.TextTemplating.Interfaces.15.0.dll
this is the latest version, not sure why it is not included in 15.0 support

(It is not included in the official Microsoft.VisualStudio.TextTemplating.15.0, which does not contain all needed files)

This is the official list of needed files per Microsoft

Microsoft.TextTemplating.Build.Tasks.dll
Microsoft.TextTemplating.targets
Microsoft.VisualStudio.TextTemplating.15.0.dll
Microsoft.VisualStudio.TextTemplating.Interfaces.15.0.dll
Microsoft.VisualStudio.TextTemplating.Modeling.15.0.dll
Microsoft.VisualStudio.TextTemplating.Sdk.Host.15.0.dll
Microsoft.VisualStudio.TextTemplating.VSHost.15.0.dll

**Comment by jazzdelightsme** [comment]
Thanks for filing this issue!

I don't think I've personally used these 15.0 files (somebody else added them to the package). I suspect that the VSHost DLL is not needed for build tasks... but it seems reasonable that the v15 Interfaces DLL should be used.

Are you willing to submit a fix?

**Comment by ghost** [comment]
I have no problem doing it . However, I would love to include all the files just because it is what Microsoft recommends. 
https://docs.microsoft.com/en-us/visualstudio/modeling/code-generation-in-a-build-process
Maybe some scenario is covered with other files.

**Comment by jazzdelightsme** [comment]
Out of curiosity... what sort of problem did this cause? (I presume just a runtime error at build time, but I'm curious about the details.) And what sort of build environment? I'm just wondering what is special/different about your configuration, since you are the first to report this problem.

(In addition to satisfying my curiosity, it will also help anybody else who happens to run into the same problem, if the details are here and thus searchable.)

FYI @HeathS

**Comment by ghost** [comment]
The problem is prevention. The machines we build on in an automated way do not have Visual Studio, so it is fair to have the same environment during the build as we have on developer's machine. Microsoft is shooting out new versions even under the same major version number quite often. We do upgrade our developer's machine but not the build environment.
Microsoft does not offer a full NuGet package (and this should be indicated somewhere in the text) as parts of it falls under EULA, you need to have Visual Studio license.
Since this is the only way of having it done, unofficial, we need to try to follow Microsoft, when you ask for 15.0 version you get the latest version. This package should do the same.
It is a matter of practice I would say.

**Comment by jazzdelightsme** [comment]
Ah, I see. Thank you for the explanation and the link to those docs.

Right now, my preference is to keep things simple. While those other DLLs are on the "official" list in the documentation, they do not seem to serve much purpose at runtime: I ran a build that used the v15 T4 transformation, with procmon running to see what DLLs were even touched, and only those that are already in the package were read.

For another data point, I opened up some of the unused binaries in ILSpy. The Interfaces.15.dll has only a few version string constants, and nothing else. The VSHost one references a ton of other assemblies like EnvDTE and other things that seem likely to only be present with full VS.

While in general I don't think "for completeness" is a bad reason, in this case I don't think it is necessary or beneficial to update the package, so I'm going to reject the PR for now. If you do run into a scenario where it would help, please do bring that up, of course.
